[package]
name = "aoc-companion"
version = "0.1.2"
edition = "2021"
authors = ["0xJoeMama"]
description = "A library used to improve your advent of code experience"
license = "MIT"

[dependencies]
regex = "1.7.0"
lazy_static = "1.5.0"
